### ISSUE TITLE
 notifier.ClearMessages(); not clearing the notifications.

### ISSUE THREAD

**Issue by goyalsachin22** [rafallopatka/ToastNotifications#62]
@raflop 
### Expected behaviour
 on calling  notifier.ClearMessages(); all the notification windows should go away.

### Actual behaviour 
none of the notifications are going away. 

### Steps to reproduce behaviour,
created a notificationManager and created instance of notifier in the constructor. calling ClearNotification which has the notifier.clearmessages();

 ### Code to reproduce behaviour

 private Notifier notifier;
        public NotificationManager()
        {
            notifier = new Notifier(cfg =>
            {
                cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(TimeSpan.FromSeconds(5), MaximumNotificationCount.FromCount(15));
                cfg.PositionProvider = new PrimaryScreenPositionProvider(Corner.BottomRight, 10, 10);
                cfg.DisplayOptions.Width = 400;
                cfg.DisplayOptions.TopMost = true;
                cfg.Dispatcher = Application.Current.Dispatcher;
            });

        }

 public void ClearNotification()
        {
            notifier.ClearMessages();
        }

**Comment by kTime** [comment]
Hi, Just wanted to add that i have found this same behaviour while using the CountBasedLifetimeSupervisor(..).

**Comment by jidel** [comment]
This seems to be an issue with threading/calling the UI thread from a background worker. Looking into the code I think this line might cause this:
https://github.com/raflop/ToastNotifications/blob/37a473f37f0f54e7cc5f01f9c159b504e1896de8/Src/ToastNotifications/Display/NotificationsDisplaySupervisor.cs#L119

Which should be:
`DelayAction.Execute(TimeSpan.FromMilliseconds(300), () => _window?.CloseNotification(notification.DisplayPart), _dispatcher);`

I did not have time to confirm this. Wrapping the library call in an own DispatcherCall seems to fix this for now.

**Comment by rafallopatka** [comment]
Fix based on @jidel solution
