### ISSUE TITLE
Wrong toasts position

### ISSUE THREAD

**Issue by cybervoodoo** [rafallopatka/ToastNotifications#68]
I use MvvmCross in my Wpf application. All views displays in one window, which is must be maximized in most UX cases. Some of views has small size, for example login view. It displays in center of window. When I try to show notification in bottom right corner it shows almost in top right one, e.g. my view has width = 250 and height = 400 and right bottom corner of toast is 400:250, if it was placed in top left corner of window (not in center), then notification was in right place relatively view's size.
IMHO, position of toasts must be calcuted from window size but not content size.

**Comment by rafallopatka** [comment]
Hi, maybe in your case, it would be better to use a PrimaryScreenPositionProvider or a custom position provider.
