### ISSUE TITLE
ShowCloseButton = false not working consistently 

### ISSUE THREAD

**Issue by jamesmccaffrey** [rafallopatka/ToastNotifications#70]
### Expected behaviour
When ShowInformation(string message, MessageOptions options) is called with options.ShowCloseButton set to false, the notification should display on every occasion with no close button. 

### Actual behaviour
On most attempts, the toast notification shall disappear and no close button is shown. This notification shall disappear after the set timeout. 

On some rare occasions, the toast notification appears with a close button and remains on display until the close button is clicked.

### Steps to reproduce behaviour
1. Create a class which holds a notifier/dispatcher etc
2. Add the method in the code below.
3. Call the method from a command (Button etc) continuously over a short period of time and observe behaviour 

### Code to reproduce behaviour
        public void ShowInformation(string message, MessageOptions opts)
        {
            opts.ShowCloseButton = false;
            notifier.ShowInformation(message, opts);
        }

**Comment by rafallopatka** [comment]
Hi,
I tried to reproduce that on the newest version, with no luck.
I used basic and configuration example, with different options and checkbox showCloseButton set to false and even with this param set to false programatically as in your example, and it worked for me.

Did you test it on latest version 2.3.3 ? If it is still happening, could you debug sources?
